export const FEEDBACK_ITEM_DETAILS_REQUEST = "FEEDBACK_ITEM_DETAILS_REQUEST";
export const FEEDBACK_ITEM_DETAILS_SUCCESS = "FEEDBACK_ITEM_DETAILS_SUCCESS";
export const FEEDBACK_ITEM_DETAILS_FAIL = "FEEDBACK_ITEM_DETAILS_FAIL";

export const FEEDBACK_SUBMIT_REQUEST = "FEEDBACK_SUBMIT_REQUEST";
export const FEEDBACK_SUBMIT_SUCCESS = "FEEDBACK_SUBMIT_SUCCESS";
export const FEEDBACK_SUBMIT_FAIL = "FEEDBACK_SUBMIT_FAIL";
